/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_smarteye_mpu_MPUCoreSDK_MainHandler */

#ifndef _Included_com_smarteye_mpu_MPUCoreSDK_MainHandler
#define _Included_com_smarteye_mpu_MPUCoreSDK_MainHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
